# Branches that trigger a build on commit
trigger:
- ide

jobs:
- job: Windows_Desktop
  pool:
    name: Azure Pipelines
    queue: windows-2019
  strategy:
    maxParallel: 4
    matrix:
      release_32:
        _configuration: Release
        _testKind: Test32
  timeoutInMinutes: 90

  steps:
    - script: eng/cibuild.cmd -configuration $(_configuration) -prepareMachine
      displayName: Build

    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\$(_configuration)'
        ArtifactName: 'Windows Desktop $(_configuration)' 
        publishLocation: Container
      continueOnError: true
      condition: not(succeeded())

