# Branches that trigger a build on commit
trigger:
- ide

jobs:
- job: Windows_Desktop
  pool:
    vmImage: windows-latest
  steps:
    - script: eng/cibuild.cmd -configuration Release -prepareMachine
      displayName: Build

    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\Release'
        ArtifactName: 'Windows Desktop Release' 
        publishLocation: Container
      continueOnError: true
      condition: not(succeeded())

