# Branches that trigger a build on commit
trigger:
- ide

jobs:
- job: Windows_Desktop
  pool:
    name: Azure Pipelines
    vmImage: windows-2019

  steps:
    - script: eng/cibuild.cmd -configuration $(_configuration) -prepareMachine
      displayName: Build

    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\$(_configuration)'
        ArtifactName: 'Windows Desktop $(_configuration)' 
        publishLocation: Container
      continueOnError: true
      condition: not(succeeded())

